# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'azure-overall' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for azure-overall
	pod 'Kingfisher', '~> 5.13'

  target 'azure-overallTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
